--Example 4-6. Extending the schema with a logging table
CREATE TABLE LOGGING (
 Logging_ID NUMBER GENERATED ALWAYS AS IDENTITY,
 EVENT_DATE TIMESTAMP NOT NULL,
 ACTION_MESSAGE VARCHAR2(255),
 CODE_LOCATION VARCHAR2(255)
 );
