--Example 8-1. Customer-specific project details in the PROJECTS table
 CREATE TABLE
 "HR"."PROJECTS"
 (
 "PROJECT_ID" NUMBER ,
 "CLIENT_PROJ" VARCHAR2(20 BYTE) ,
 "HOURS_WORKED" NUMBER ,
 "EMPLOYEE_ID" NUMBER ,
 "CONTACT" VARCHAR2(100 BYTE),
 "RATE" NUMBER(19,4) ,
 "REVENUE" NUMBER(19,4) ,
 "TAX" NUMBER(19,4) ,
 "RECIPIENT" VARCHAR2(100 BYTE),
 CONSTRAINT "FK_EMPLOYEE_ID1"
 FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "HR"."EMPLOYEES"
 ("EMPLOYEE_ID") ENABLE
 );
 
 INSERT INTO PROJECTS(PROJECT_ID, CLIENT_PROJ, HOURS_WORKED, EMPLOYEE_ID,
CONTACT, RATE, REVENUE, TAX, RECIPIENT)
 VALUES(1, 'Project', 10, 107, 'mark@provider.com', 100.00,
 1000, 0.15, 'mary@acme.com');
